apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dispatch
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - serviceaccount.yaml
  - external-infra.yaml
  - networkpolicy.yaml
  - delivery-api.yaml
  - dispatch-worker.yaml
  - tracking-ingest.yaml
  - tracking-projector.yaml
  - notification-worker.yaml
