apiVersion: v1
kind: ConfigMap
metadata:
  name: lunchrush-config
  namespace: {{ .Values.namespace }}
data:
  KAFKA_BROKERS: "redpanda-external:{{ .Values.externalInfra.redpanda.port }}"
  DATABASE_URL: "postgres://lunchrush:lunchrush@postgres-external:{{ .Values.externalInfra.postgres.port }}/lunchrush?sslmode=disable"
  REDIS_ADDR: "redis-external:{{ .Values.externalInfra.redis.port }}"
  NOTIFICATION_PROVIDER_URL: "http://dependency-simulator-external:{{ .Values.externalInfra.dependencySimulator.port }}"
  OFFER_TTL_SECONDS: {{ .Values.config.offerTTLSeconds | quote }}
